#! /usr/bin/python3

import argparse, json, os, pathlib, zipfile, zlib

GGGG_REPO_PATH = pathlib.Path(os.path.realpath(__file__)).parent
DEFAULT_SKELETON_PATH = pathlib.Path(GGGG_REPO_PATH, 'autograder-skeleton')
DEFAULT_TEMPLATE_REPO_PATH = pathlib.Path.cwd()
DEFAULT_OVERWRITE_FILENAMES = []
DEFAULT_ZIP_PATH = 'autograder.zip'

RUN_AUTOGRADER_FILENAME = 'run_autograder'

def make_autograder(verbose,
                    skeleton_path,
                    template_repo_path,
                    overwrite_filenames,
                    zip_path):
    if not (isinstance(verbose, bool) and
            isinstance(skeleton_path, pathlib.Path) and
            isinstance(template_repo_path, pathlib.Path) and
            isinstance(overwrite_filenames, list) and
            all([isinstance(x, str) for x in overwrite_filenames]) and
            isinstance(zip_path, str)):
        raise TypeError
    
    with zipfile.ZipFile(zip_path,
                         'w',
                         compression=zipfile.ZIP_DEFLATED,
                         compresslevel=zlib.Z_DEFAULT_COMPRESSION) as zip:

        if verbose:
            print('creating ' + zip_path)
        
        # copy skeleton files
        for path in skeleton_path.iterdir():
            filename = path.name
            if verbose:
                print('adding ' + filename)
            zip.write(path, filename)

        # create overwrite.json
        json_str = json.dumps(overwrite_filenames)
        if verbose:
            print('creating overwrite.json with contents "' + json_str + '"')
        zip.writestr('overwrite.json', json_str)

        # copy overwrite files
        for filename in overwrite_filenames:
            path = os.path.join(template_repo_path, filename)
            if verbose:
                print('adding ' + path)
            zip.write(path, filename)

def main():
    parser = argparse.ArgumentParser(description='create a GradeScope autograder .ZIP file')
    parser.add_argument('--skeleton',
                        help='path to gggg/autograder-skeleton directory (default: ' + str(DEFAULT_SKELETON_PATH) + ')',
                        default=DEFAULT_SKELETON_PATH)
    parser.add_argument('--repo',
                        help='path to template github repo, the one you distribute to students (default: .)',
                        default=DEFAULT_TEMPLATE_REPO_PATH)
    parser.add_argument('--overwrite', '-f',
                        help='filename to overwrite from template prior to grader, for tamper-proofing (may be repeated)',
                        default=DEFAULT_OVERWRITE_FILENAMES,
                        action='append')
    parser.add_argument('--output', '-o',
                        help='path for output .zip (default: ' + str(DEFAULT_ZIP_PATH) + ')',
                        default=DEFAULT_ZIP_PATH)

    args = parser.parse_args()

    make_autograder(True,
                    pathlib.Path(args.skeleton),
                    pathlib.Path(args.repo),
                    args.overwrite,
                    args.output)

if __name__ == '__main__':
    main()
